INSERT INTO MEDICOENTITY (ID,CONTRASENA,LOGIN,NAME,NOMBE,TIPO,CALENDARIO_ID)
VALUES (1,'LOL','j.wilcken','','Jorgen Wilcken',1,null);
INSERT INTO MEDICOENTITY (ID,CONTRASENA,LOGIN,NAME,NOMBRE,TIPO,CALENDARIO_ID)
VALUES (2,'obgyn','i.maldonado','','Ivette Maldonado',1,null);
INSERT INTO MEDICOENTITY (ID,CONTRASENA,LOGIN,NAME,NOMBRE,TIPO,CALENDARIO_ID)
VALUES (3,'artroscopia','j.marino','','Jaime Mariño',1,null);
INSERT INTO MEDICOENTITY (ID,CONTRASENA,LOGIN,NAME,NOMBRE,TIPO,CALENDARIO_ID)
VALUES (4,'anato','r.ruedan','','Roberto Rueda',2,null);
INSERT INTO MEDICOENTITY (ID,CONTRASENA,LOGIN,NAME,NOMBRE,TIPO,CALENDARIO_ID)
VALUES (5,'anato','jd.hernandez','','Juan David Hernandez',2,null);